<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\BlogController::index' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CategoryController::delete' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController::edit' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController::index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController::show' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\BlogController:index' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CategoryController:delete' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController:edit' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}, 'App\\Controller\\CategoryController:index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController:show' => function () {
    return ($this->privates['.service_locator.koD3dBr'] ?? $this->load('get_ServiceLocator_KoD3dBrService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
