<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.z2T0V0W' shared service.

return $this->privates['.service_locator.z2T0V0W'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('tag' => function (): \App\Entity\Tag {
    return ($this->privates['.errored..service_locator.z2T0V0W.App\Entity\Tag'] ?? $this->load('getTagService.php'));
}));
