<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.koD3dBr' shared service.

return $this->privates['.service_locator.koD3dBr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('category' => function (): \App\Entity\Category {
    return ($this->privates['.errored..service_locator.koD3dBr.App\Entity\Category'] ?? $this->load('getCategoryService.php'));
}));
