<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ur1lQtD' shared service.

return $this->privates['.service_locator.Ur1lQtD'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('tagRepository' => function (): \App\Repository\TagRepository {
    return ($this->privates['App\Repository\TagRepository'] ?? $this->load('getTagRepositoryService.php'));
}));
