<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDeFWxQ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDeFWxQ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMDeFWxQ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMDeFWxQ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMDeFWxQ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MDeFWxQ',
    'container.build_id' => 'db2376f3',
    'container.build_time' => 1543248534,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDeFWxQ');
