<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsBpRRz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsBpRRz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCsBpRRz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCsBpRRz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCsBpRRz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CsBpRRz',
    'container.build_id' => 'dcde3b15',
    'container.build_time' => 1543855328,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsBpRRz');
